/**
 * Slow-tier balance batch runner — the canonical source for
 * data/balance_metrics_latest.json (replaces the historical Python snapshot,
 * archived at data/balance_metrics_python_reference.json).
 *
 * Run with:   pnpm sim:balance
 * Options:    SIM_RUNS=5000 SIM_RANDOM_RUNS=2000 SIM_SEED=920000 SIM_OUT=... pnpm sim:balance
 *
 * Runs the skilled greedy-EV policy and the uniform-random policy over seeded
 * dungeons and writes both summaries. The random policy is the design gate for
 * "random play survives most of L1 but rarely passes the L1 boss"; the skilled
 * policy is the (bot-biased, see loot policy weights) upper reference. For
 * engine-constant experiments, run this with the same SIM_SEED on both
 * versions and diff the outputs — dungeons are identical per seed.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { it } from "vitest";
import { estimateReactWinRate, randomPolicy, skilledPolicy, type SimSummary } from "../src/features/playtest/engine";

const RUNS = Math.max(1, Number(process.env.SIM_RUNS || 5000));
const RANDOM_RUNS = Math.max(1, Number(process.env.SIM_RANDOM_RUNS || Math.min(RUNS, 2000)));
const SEED = Number(process.env.SIM_SEED || 920000);
const OUT = resolve(process.cwd(), process.env.SIM_OUT || "data/balance_metrics_latest.json");

function conditional(clear: number, reach: number): number {
  return reach > 0 ? clear / reach : 0;
}

function section(summary: SimSummary) {
  return {
    sample: {
      runs: summary.runs,
      seed: summary.seed,
      policy: summary.policy,
      wins: summary.wins,
      deaths: summary.deaths,
      timeouts: summary.timeouts,
    },
    core_metrics: {
      win_rate: summary.winRate,
      avg_rooms_cleared: summary.avgRoomsCleared,
      rooms_p50: summary.roomsP50,
      rooms_p75: summary.roomsP75,
      rooms_p90: summary.roomsP90,
      rooms_p95: summary.roomsP95,
      rooms_p99: summary.roomsP99,
    },
    floor_reach_rates: {
      reach_l2_rate: summary.reachL2Rate,
      reach_l3_rate: summary.reachL3Rate,
      reach_l4_rate: summary.reachL4Rate,
      reach_l5_rate: summary.reachL5Rate,
    },
    boss_gates: {
      reach_l1_boss_rate: summary.reachL1BossRate,
      clear_l1_boss_rate: summary.clearL1BossRate,
      reach_l2_boss_rate: summary.reachL2BossRate,
      clear_l2_boss_rate: summary.clearL2BossRate,
      reach_l3_boss_rate: summary.reachL3BossRate,
      clear_l3_boss_rate: summary.clearL3BossRate,
      reach_l4_boss_rate: summary.reachL4BossRate,
      clear_l4_boss_rate: summary.clearL4BossRate,
      reach_l5_boss_rate: summary.reachL5BossRate,
      clear_l5_boss_rate: summary.clearL5BossRate,
    },
    conditional_boss_pass_rates: {
      l1_boss_clear_given_reached: conditional(summary.clearL1BossRate, summary.reachL1BossRate),
      l2_boss_clear_given_reached: conditional(summary.clearL2BossRate, summary.reachL2BossRate),
      l3_boss_clear_given_reached: conditional(summary.clearL3BossRate, summary.reachL3BossRate),
      l4_boss_clear_given_reached: conditional(summary.clearL4BossRate, summary.reachL4BossRate),
      l5_boss_clear_given_reached: conditional(summary.clearL5BossRate, summary.reachL5BossRate),
    },
    deaths_by_level: summary.deathsByLevel,
    deaths_by_room_kind: summary.deathsByRoomKind,
    action_counts: summary.actions,
  };
}

it(`writes ${OUT} (${RUNS} skilled + ${RANDOM_RUNS} random runs, seed ${SEED})`, () => {
  const startedAt = Date.now();
  const skilled = estimateReactWinRate(RUNS, SEED, skilledPolicy);
  const random = estimateReactWinRate(RANDOM_RUNS, SEED, randomPolicy);

  const report = {
    version: "0.2.0",
    updated_at: new Date().toISOString().slice(0, 10),
    status: "react_engine_canonical",
    canonical_runtime: "src/features/playtest/engine",
    generator: "pnpm sim:balance (tools/simBalanceReport.ts)",
    character: "Balanced Swordsman",
    build: "balanced",
    starting_weapon: "Iron Sword",
    encounter_model: "randomized_power_bands_with_strict_bosses",
    skilled: section(skilled),
    random_play: section(random),
    weapon_lift_sample: {
      status: "pending_react_rerun",
      note: "Historical Python weapon-lift rows live in data/balance_metrics_python_reference.json; rerun through the React engine before comparing weapons.",
    },
    interpretation: [
      "Generated by the canonical React engine simulator (src/features/playtest/engine/sim.ts).",
      "Skilled policy is a greedy one-step-EV bot: treat its win rate as a biased lower bound on skilled human play.",
      "Random policy is the gate for 'random play survives most of L1 but rarely passes the L1 boss'.",
      "Timeouts should be ~0 now that COMBAT.maxCombatRounds is enforced; a nonzero count means a stalemate loop regressed.",
      "The historical Python snapshot is archived at data/balance_metrics_python_reference.json and is not a tuning target.",
    ],
  };

  writeFileSync(OUT, JSON.stringify(report, null, 2) + "\n");
  // eslint-disable-next-line no-console
  console.log(
    `wrote ${OUT} in ${((Date.now() - startedAt) / 1000).toFixed(1)}s — skilled win ${(skilled.winRate * 100).toFixed(2)}% ` +
      `(timeouts ${skilled.timeouts}), random win ${(random.winRate * 100).toFixed(2)}%, random L1-boss clear ${(random.clearL1BossRate * 100).toFixed(2)}%`
  );
});
